[make] first implementation
rustcoreutils/posixutils-rs pull request #160
Opened 2024-07-05 09:31 UTC by Wandalen

2024-10-23 13:24 UTC, Wandalen commented
@jgarzik ready for review

2024-10-23 14:16 UTC, jgarzik requested changes
Mostly looks OK.  Some minor changes.

2024-10-23 14:16 UTC, jgarzik commented on m4/tests/integration_test.rs
> +    let output = run_command(&Path::new("fixtures/integration_tests/bsd.m4"));
merge error.  This PR should not touch m4/

2024-10-23 14:16 UTC, jgarzik commented on plib/src/testing.rs
> -
Change rejected -- This change deletes some tests _across all utilities_.

2024-10-24 12:56 UTC, Wandalen commented
@jgarzik took into account. is there anything?

2024-10-26 01:42 UTC, merged