[talk] full implementation
rustcoreutils/posixutils-rs pull request #256
Opened 2024-09-26 10:40 UTC by Wandalen

2024-09-26 13:41 UTC, jgarzik requested changes
Well done on the dependencies.  Only minor comments for now.

2024-09-26 13:41 UTC, jgarzik commented on users/Cargo.toml
> +binrw = "0.14.0"
remove micro version in deps.  e.g. "1.0" rather than "1.0.63"

2024-09-26 13:41 UTC, jgarzik commented on users/talk.rs
> +extern crate plib;
extern crate no longer needed.

2024-09-26 13:41 UTC, jgarzik commented on users/talk.rs
> +fn main() -> Result<(), Box<dyn std::error::Error>> {
`main` should always be the last function in the program.

2024-09-27 16:17 UTC, Wandalen commented
@jgarzik done

2024-09-27 19:47 UTC, merged