[newgrp] full implementation
rustcoreutils/posixutils-rs pull request #347
Opened 2024-10-19 07:07 UTC by Wandalen

2024-10-19 07:36 UTC, Wandalen commented
@jgarzik ready for review

2024-10-19 13:13 UTC, jgarzik requested changes
small cleanups needed.  no major problems.

2024-10-19 13:13 UTC, jgarzik commented on users/Cargo.toml
> +libcrypt-rs = "0.1.2"
Always delete the micro version from dependencies.

2024-10-19 13:13 UTC, jgarzik commented on users/newgrp.rs
> +}
See datetime/cal.rs for an example of the new style of `struct Args` with translation support added.

Follow cal.rs style of struct Args.

2024-10-19 13:13 UTC, jgarzik commented on users/newgrp.rs
> +}
use plib::curuser::login_name() ?

2024-10-19 13:13 UTC, jgarzik commented on users/newgrp.rs
> +}
use plib::curuser::tty?

2024-10-19 13:13 UTC, jgarzik commented on users/newgrp.rs
> +    let mut exit_code = 0;
new style:  put translation setup *before* Args parsing.

2024-10-23 13:29 UTC, Wandalen commented
@jgarzik also ready

2024-10-23 14:07 UTC, jgarzik approved these changes

2024-10-23 14:07 UTC, merged